### ISSUE TITLE
Update Website Banner

### ISSUE THREAD

**Issue by alvoght-renci** [stagecc/interim-bdc-website#144]
Update the "alert" banner on the website to REMOVE the RECOVER message and include the following: 

NHLBI BioData Catalyst® (BDC) supports data and analysis in a secure, FISMA-moderate environment. BDC security controls adhere to [NIH’s Implementation Update for Data Management and Access Practices Under the Genomic Data Sharing Policy (NOT-OD-24-157)](https://grants.nih.gov/grants/guide/notice-files/NOT-OD-24-157.html).

**Comment by alvoght-renci** [comment]
@suejinkim20 

quick update - since this is more informational than an alert, could we change the colors from red to potentially a light blue?

**Comment by suejinkim20** [comment]
Here is a screenshot of what a blue banner might look like. Does this align with what you had in mind, @alvoght-renci? Let me know if this works, or if you have feedback!

![Screenshot 2024-12-19 at 11 55 11 AM](https://github.com/user-attachments/assets/6caed9be-9f63-4c0c-99b6-86ef779b3f3c)

**Comment by alvoght-renci** [comment]
This looks good! Thanks, @suejinkim20

**Comment by alvoght-renci** [comment]
Please verify that the blue background and the blue link against it are 508 compliant :) @suejinkim20
