### ISSUE TITLE
Add Page for EEP to BDC Website

### ISSUE THREAD

**Issue by alvoght-renci** [stagecc/interim-bdc-website#50]
@suejinkim20  - As discussed briefly on Slack: Create a very basic page on the BDC website to showcase eight members of the BDC EEP (External Expert Panel). Each person should have a space for a photo and biography. 

Lauren is currently gathering photos, bios, and receiving approval from all eight members. While that is going on, you could work on the page and then just plug in the info once it's available. Lauren has already approved a layout; essentially, something like the blog "contributor template" with the people in boxes with photo left aligned in circle and text on the right _BUT_ without the "read more" (ie just all text displayed) is fine.

Let me know if you have questions. I will update this issue with any updates from Lauren as she receives the member photos and bios. I believe her goal is before end of September.

**Comment by mbwatson** [comment]
@alvoght-renci do we know where this new page will live in the sitemap? will it get a top-level menu item?

**Comment by alvoght-renci** [comment]
the content and headshots for this page is now available; i have added what you will need to Google Drive: https://drive.google.com/drive/folders/14mGa4n-HEaxZuhUaiKixoX6KrSy4_4QM?usp=drive_link

**Comment by alvoght-renci** [comment]
this page looks great, and is approved to be published to the website

https://staging.biodatacatalyst.nhlbi.nih.gov/about/overview/eep/
