### ISSUE TITLE
Add "Platform Name" fields to Cloud Credit Requests Form for Pilot Funds

### ISSUE THREAD

**Issue by alvoght-renci** [stagecc/interim-bdc-website#56]
Add required field for platform name to the form for "Cloud Credit Requests" on the [Usage Costs page](https://biodatacatalyst.nhlbi.nih.gov/user-resources/usage-costs/#usage-costs).

Question: "BDC users may request one of the following:," and user selects "**NHLBI BDC Pilot Funding Program**" a new field appears, "Preferred analysis platform." If user selects:

- [x] BDC Seven Bridges --> new **required** field should appear, "BDC-Seven Bridges Username (create account [here](https://sb-biodatacatalyst.readme.io/docs/sign-up-for-biodata-catalyst-powered-by-seven-bridges))"
- [x] Also, update "BDC Seven Bridges" to "BDC-Seven Bridges" (note the dash between 'BDC' and 'Seven')

- [x] BDC-Terra --> new **required** field should appear, "BDC-Terra Google identity (create account [here](https://support.terra.bio/hc/en-us/articles/360028235911-How-to-register-on-Terra-Google-SSO))"

- [x] Both BDC Seven Bridges and BDC-Terra --> both fields for BDC-Seven Bridges and BDC-Terra usernames should appear (both required)
- [x] Again, update "BDC Seven Bridges" to "BDC-Seven Bridges" (dash between 'BDC' and 'Seven')

This logic was used on the previous version of this form before the interim website went live; you can view a screen recording of it [here](https://drive.google.com/file/d/1iG8mDxhOCqNZE_0OYuQ8BinhemEa-sd-/view?resourcekey).

**Comment by mbwatson** [comment]
tickets are created with this new detail added to the corresponding fields and to the ticket description ![2024-09-20_08-30](https://github.com/user-attachments/assets/f91b516c-d870-4710-8bda-218d8cef259e)
