### ISSUE TITLE
Bug: Some pages do not have SEO titles

### ISSUE THREAD

**Issue by suejinkim20** [stagecc/interim-bdc-website#66]
The following pages do not utilize the title prop in the <PageContent> component. 

- [x] Dug / Disease, Phenotype, Biological Process, or Anatomical Entity Search Page: `/use-bdc/explore-data/dug`
- [x] Events:
  - [x] Upcoming Events: `/news-and-events/events`
  - [x] Past Events: `/news-and-events/events/archive/`
  - [x] Single Event Pages: `/news-and-events/events/[date]/[slug]`
- [x] Tag pages
- [x] Single Latest Update (blog) Pages

**Comment by mbwatson** [comment]
i think you've got them all!

i noticed some places we aren't fully utilizing existing functionality, so keep in mind that PageContent takes care of  SEO as well as adding a Title to the page (unless `hideTitle` is set, of course), so things like [this](https://github.com/stagecc/interim-bdc-website/blob/e15d30d287d3f1feb01534845d592887314e5b76/src/templates/events/past-events-template.jsx#L18)

```
<PageContent width="95%" maxWidth="800px">
  <Title>Upcoming Events</Title>
```

can be simplified to

```
<PageContent width="95%" maxWidth="800px" title="Upcoming Events">
```

on that note, the PageContent component's defaults let this simplify down more to only

```
<PageContent maxWidth="800px" title="Upcoming Events">
```
