### ISSUE TITLE
Add RECOVER Banner to BDC Website

### ISSUE THREAD

**Issue by NatVolk** [stagecc/interim-bdc-website#83]
ASAP please as per the attached
[RECOVER Peds Data in BDC - BDC web (need RN & YT link)[23].docx](https://github.com/user-attachments/files/17168978/RECOVER.Peds.Data.in.BDC.-.BDC.web.need.RN.YT.link.23.docx)

**Comment by alvoght-renci** [comment]
1. Missing a space in the banner between “BDC.” and “Learn” . Add a space.
2. Question: Is the gradient just a new style you are trying? Wondering if we should make it darker red to lighter red or something a bit different than the red to yellow (Lauren didn’t seem to love it, but also doesn’t seem to care too much). Defer to you on changing or not.
